name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  prepare:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ matrix.node-version }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: node-${{ matrix.node-version }}-npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Save node_modules
        uses: actions/upload-artifact@v2
        with:
          name: node_modules-${{ matrix.node-version }}
          path: node_modules

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Download node_modules
        uses: actions/download-artifact@v2
        with:
          name: node_modules-${{ matrix.node-version }}
      - run: npm run build --if-present

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Download node_modules
        uses: actions/download-artifact@v2
        with:
          name: node_modules-${{ matrix.node-version }}
      - run: npm test

  e2e-test:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Download node_modules
        uses: actions/download-artifact@v2
        with:
          name: node_modules-${{ matrix.node-version }}
      - uses: cypress-io/github-action@v6
      - name: Run e2e tests
        run: npx nx run e2e:e2e
