name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  prepare:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: node-${{ matrix.node-version }}-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Restore node_modules from cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
      - run: npm run build --if-present

  test:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Restore node_modules from cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
      - run: npm test

  e2e-test:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Restore node_modules from cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
      - run: npx nx run e2e:e2e
